name: Capstone Project Workflow

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs: 
  testJob:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Load repository
      uses: actions/checkout@v3
      
    - name: Install dependencies
      run: |
            cd capstone_project/hello-world/
            npm install
            #pwd
            #ls
      
    - name: Run Tests
      run: |
            cd capstone_project/hello-world/
            npm run test
       
    - name: Check for success
      if: ${{ success() }}
      run: echo "Tests Succeeded!"
      
  buildJob:
    needs: testJob
    runs-on: ubuntu-latest
    if: ${{ needs.testJob.result == 'success' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Build Docker Image
      run: |
            cd capstone_project/hello-world/
            docker build -t hello-world-img .
            docker run --name hello-world -p 3000:3000 -itd hello-world-img
            docker ps
            docker logs hello-world
